import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  loginScreen: {
    backgroundRepeat: "no-repeat",
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    fontFamily: "Arial, sans-serif",
  },
  loginCard: {
    background: "rgba(255, 255, 255, 0.06)",
    width: "100%",
    maxWidth: 440,
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: 28,
    padding: 32,
    boxSizing: "border-box",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    backdropFilter: "blur(12px)",
    color: "#ffffff",
  },
  loginBadge: {
    alignSelf: "flex-start",
    background: "#111827",
    color: "#ffffff",
    borderRadius: 999,
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.12em",
  },
  loginTitle: {
    margin: 0,
    fontSize: 32,
    lineHeight: 1.1,
    fontWeight: 800,
    color: "#ffffff",
    letterSpacing: "-0.04em",
  },
  loginSubtitle: {
    margin: 0,
    fontSize: 15,
    lineHeight: 1.6,
    color: "rgba(255,255,255,0.75)",
  },
  loginInput: {
    width: "100%",
    borderRadius: 14,
    border: "1px solid rgba(148,163,184,0.26)",
    padding: "14px 16px",
    fontSize: 16,
    outline: "none",
    boxSizing: "border-box",
    background: "#ffffff",
    color: "#111827",
  },
  loginError: {
    fontSize: 13,
    color: "#dc2626",
    fontWeight: 600,
    minHeight: 18,
  },
  loginButton: {
    border: "none",
    borderRadius: 14,
    padding: "14px 18px",
    background: "linear-gradient(135deg, #f59e0b, #dc2626)",
    color: "#ffffff",
    fontSize: 15,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: "0 16px 32px rgba(245,158,11,0.30)",
  },
  appShell: {
    backgroundPosition: "center",
    backgroundSize: "cover",
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    display: "flex",
    minHeight: "100vh",
    background: "#07090f",
    color: "#f8fafc",
    fontFamily: "Arial, sans-serif",
    overflowX: "hidden",
    position: "relative",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  appShellMobile: {
    flexDirection: "column",
    alignItems: "stretch",
    width: "100%",
    maxWidth: "100%",
    paddingLeft: 0,
    marginLeft: 0,
  },
  mainHideoutHeroPanel: {
    backdropFilter: "blur(12px)",
    background: "rgba(255, 255, 255, 0.06)",
    position: "relative",
    overflow: "hidden",
    borderRadius: 30,
    minHeight: 340,
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  mainHideoutToolCloud: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    opacity: 0.14,
  },
  mainHideoutTool: {
    position: "absolute",
    fontSize: 54,
    filter: "drop-shadow(0 16px 18px rgba(0,0,0,0.34))",
  },
  mainHideoutHeroOverlay: {
    position: "relative",
    zIndex: 2,
    minHeight: 340,
    padding: "clamp(22px, 5vw, 48px)",
    display: "flex",
    alignItems: "center",
    color: "#ffffff",
    background: "linear-gradient(90deg, rgba(2,6,23,0.78), rgba(2,6,23,0.34))",
  },
  gpPoliceLogoMark: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 108,
    height: 108,
    borderRadius: 28,
    background: "linear-gradient(135deg, #fbbf24 0%, #f59e0b 45%, #111827 46%, #020617 100%)",
    boxShadow: "0 18px 34px rgba(0,0,0,0.34)",
    border: "1px solid rgba(255,255,255,0.22)",
  },
  gpPoliceLogoShield: {
    width: 82,
    minHeight: 82,
    borderRadius: "20px 20px 28px 28px",
    background: "linear-gradient(180deg, #111827 0%, #020617 100%)",
    color: "#ffffff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    border: "2px solid rgba(251,191,36,0.9)",
    textAlign: "center",
    padding: 8,
    boxSizing: "border-box",
  },
  gpPoliceLogoTop: {
    fontSize: 24,
    fontWeight: 950,
    letterSpacing: "-0.08em",
    lineHeight: 1,
    color: "#fbbf24",
  },
  gpPoliceLogoMiddle: {
    fontSize: 12,
    fontWeight: 950,
    letterSpacing: "0.08em",
    lineHeight: 1.2,
  },
  gpPoliceLogoBottom: {
    fontSize: 7,
    fontWeight: 900,
    letterSpacing: "0.1em",
    color: "rgba(255,255,255,0.75)",
    marginTop: 4,
  },
  mainHideoutHeroBadge: {
    display: "inline-flex",
    width: "fit-content",
    borderRadius: 999,
    padding: "8px 12px",
    background: "rgba(127,29,29,0.42)",
    border: "1px solid rgba(251,191,36,0.38)",
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    fontWeight: 950,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  mainHideoutHeroTitle: {
    margin: 0,
    fontSize: "clamp(34px, 6vw, 64px)",
    lineHeight: 0.95,
    fontWeight: 950,
    letterSpacing: "-0.06em",
    color: "#ffffff",
    textShadow: "0 12px 34px rgba(0,0,0,0.55)",
  },
  mainHideoutHeroTagline: {
    marginTop: 6,
    color: "rgba(255,255,255,0.75)",
    fontSize: 13,
    fontWeight: 950,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  mainHideoutHeroSubtext: {
    margin: 0,
    maxWidth: 680,
    color: "rgba(255,255,255,0.75)",
    fontSize: "clamp(15px, 2vw, 19px)",
    lineHeight: 1.55,
    fontWeight: 750,
  },
  mobileTopBar: {
    position: "sticky",
    top: 0,
    left: 0,
    zIndex: 40,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 16px",
    background: "rgba(15,23,42,0.96)",
    borderBottom: "1px solid rgba(148,163,184,0.18)",
    backdropFilter: "blur(12px)",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
    flexShrink: 0,
  },
  mobileMenuButton: {
    border: "1px solid rgba(255,255,255,0.10)",
    background: "rgba(255,255,255,0.07)",
    color: "#ffffff",
    borderRadius: 12,
    padding: "10px 14px",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    flexShrink: 0,
  },
  mobileTopBarTitleWrap: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    gap: 4,
  },
  mobileTopBarBadge: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.14em",
    color: "#fbbf24",
  },
  mobileTopBarTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: "#ffffff",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  sidebar: {
    width: 320,
    flexShrink: 0,
    background: "linear-gradient(180deg, rgba(15,23,42,0.98) 0%, rgba(17,24,39,0.98) 100%)",
    color: "#ffffff",
    padding: 22,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 18,
    borderRight: "1px solid rgba(148,163,184,0.16)",
    boxShadow: "18px 0 40px rgba(2,6,23,0.28)",
    position: "sticky",
    top: 0,
    alignSelf: "flex-start",
    minHeight: "100vh",
    zIndex: 35,
  },
  sidebarMobile: {
    position: "fixed",
    top: 0,
    left: 0,
    bottom: 0,
    width: "min(320px, 84vw)",
    maxWidth: "84vw",
    minHeight: "100dvh",
    overflowY: "auto",
    borderRight: "1px solid rgba(148,163,184,0.18)",
    boxShadow: "24px 0 48px rgba(2,6,23,0.42)",
  },
  mobileMenuBackdrop: {
    position: "fixed",
    inset: 0,
    border: "none",
    background: "rgba(2,6,23,0.52)",
    padding: 0,
    margin: 0,
    zIndex: 30,
    cursor: "pointer",
  },
  sidebarHeader: {
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    paddingBottom: 18,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  brandTitle: {
    fontSize: 30,
    fontWeight: 800,
    letterSpacing: "-0.05em",
    marginBottom: 2,
    lineHeight: 1,
  },
  brandSubtitle: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.4,
    fontWeight: 700,
  },
  brandMeta: {
    fontSize: 12,
    opacity: 0.64,
    marginTop: 2,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.4,
  },
  navList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  navButton: {
    background: "rgba(255,255,255,0.07)",
    color: "#e5e7eb",
    border: "1px solid rgba(255,255,255,0.10)",
    borderRadius: 18,
    padding: "14px 16px",
    textAlign: "left",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 700,
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.04)",
  },
  navButtonActive: {
    background: "linear-gradient(135deg, #f59e0b, #dc2626)",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#ffffff",
    boxShadow: "0 16px 28px rgba(245,158,11,0.30)",
  },
  sidebarStats: {
    display: "grid",
    gap: 10,
    marginTop: "auto",
  },
  sidebarStatCard: {
    background: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    padding: 14,
    border: "1px solid rgba(255,255,255,0.08)",
  },
  sidebarStatLabel: {
    fontSize: 12,
    opacity: 0.8,
    marginBottom: 6,
  },
  sidebarStatValue: {
    fontSize: 22,
    fontWeight: 700,
  },
  mainContent: {
    flex: 1,
    padding: 28,
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    marginLeft: 0,
  },
  mainContentMobile: {
    padding: "16px 16px 170px",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    marginLeft: 0,
    paddingLeft: 16,
    paddingRight: 16,
    alignSelf: "stretch",
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  pageWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
    paddingBottom: 180,
  },
  pageHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  pageTitle: {
    margin: 0,
    fontSize: "clamp(28px, 6vw, 40px)",
    fontWeight: 800,
    letterSpacing: "-0.06em",
    color: "#ffffff",
    textShadow: "0 14px 34px rgba(0,0,0,0.55)",
    lineHeight: 1.02,
  },
  pageSubtitle: {
    margin: 0,
    fontSize: 15,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.6,
    maxWidth: 900,
  },
  card: {
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: 28,
    padding: "clamp(20px, 3vw, 28px)",
    boxShadow: "0 24px 80px rgba(0,0,0,0.52), inset 0 0 46px rgba(245,158,11,0.08)",
    border: "1px solid rgba(251,191,36,0.24)",
    color: "#ffffff",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
  },
  premiumFirePanel: {
    backgroundImage: `
  linear-gradient(90deg,
    rgba(3, 7, 18, 0.60) 0%,
    rgba(3, 7, 18, 0.42) 30%,
    rgba(3, 7, 18, 0.12) 60%,
    rgba(3, 7, 18, 0.38) 100%
  ),
  linear-gradient(180deg,
    rgba(3, 7, 18, 0.00) 0%,
    rgba(3, 7, 18, 0.28) 100%
  ),
  url("/images/hero.png")
`,
    backgroundSize: "cover",
    backgroundPosition: "center center",
    backgroundRepeat: "no-repeat",
    backgroundBlendMode: "normal, multiply, normal",
    position: "relative",
    overflow: "hidden",
    minHeight: 260,
    border: "1px solid rgba(251,191,36,0.34)",
    boxShadow: "0 0 36px rgba(245, 158, 11, 0.20), inset 0 0 80px rgba(0,0,0,0.75)",
  },
  cardInset: {
    marginTop: 20,
    paddingTop: 20,
    borderTop: "1px solid rgba(251,191,36,0.18)",
  },
  supplierPageToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  supplierListLayout: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 280px), 1fr))",
    gap: 12,
    marginTop: 16,
  },
  supplierSummaryMeta: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  supplierActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 10,
  },
  supplierDetailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 220px), 1fr))",
    gap: 12,
  },
  sectionGroupStack: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  sectionGroupCard: {
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 14,
    padding: 16,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
  },
  sectionGroupHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  sectionGroupTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 700,
    color: "#ffffff",
  },
  sectionGroupSubtotal: {
    fontSize: 14,
    fontWeight: 700,
    color: "#ffffff",
  },
  sectionTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 700,
    color: "#ffffff",
  },
  sectionTitleSmall: {
    margin: 0,
    fontSize: 20,
    fontWeight: 700,
    color: "#ffffff",
  },
  sectionSubtitle: {
    margin: 0,
    fontSize: 14,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.6,
  },
  formWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    marginTop: 16,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 220px), 1fr))",
    gap: 16,
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  formGroupButton: {
    display: "flex",
    alignItems: "flex-end",
    minWidth: 0,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "rgba(255,255,255,0.75)",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    border: "1px solid rgba(251,191,36,0.22)",
    borderRadius: 10,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: "#ffffff",
    color: "#111827",
  },
  select: {
    width: "100%",
    padding: "12px 14px",
    border: "1px solid rgba(251,191,36,0.22)",
    borderRadius: 10,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: "#ffffff",
    color: "#111827",
  },
  buttonRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  primaryButton: {
    background: "linear-gradient(135deg, #f59e0b, #dc2626)",
    color: "#ffffff",
    border: "none",
    borderRadius: 16,
    padding: "13px 18px",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: "0 14px 28px rgba(245,158,11,0.26)",
    minHeight: 48,
  },
  secondaryButton: {
    background: "rgba(255,255,255,0.07)",
    color: "#ffffff",
    border: "1px solid rgba(255,255,255,0.10)",
    borderRadius: 16,
    padding: "13px 18px",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    minHeight: 48,
  },
  smallButton: {
    background: "rgba(255,255,255,0.07)",
    color: "#ffffff",
    border: "1px solid rgba(255,255,255,0.10)",
    borderRadius: 12,
    padding: "10px 13px",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  },
  smallDangerButton: {
    background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: 12,
    padding: "10px 13px",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineButtonRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  summaryBar: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 12,
  },
  summaryItem: {
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 18,
    padding: 16,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  summaryLabel: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    marginBottom: 6,
    fontWeight: 600,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ffffff",
  },
  pricingGuidanceBox: {
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 22,
    padding: 18,
    background: "rgba(255, 255, 255, 0.06)",
    display: "grid",
    gap: 14,
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  pricingGuidanceBoxWarning: {
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255, 255, 255, 0.06)",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  pricingGuidanceHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  pricingGuidanceTitle: {
    fontSize: 20,
    fontWeight: 900,
    color: "#ffffff",
  },
  pricingGuidanceBadge: {
    borderRadius: 999,
    padding: "8px 12px",
    background: "#111827",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: 900,
  },
  pricingGuidanceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 12,
  },
  pricingInput: {
    width: "100%",
    border: "1px solid rgba(148,163,184,0.26)",
    borderRadius: 14,
    padding: "10px 12px",
    fontSize: 16,
    fontWeight: 800,
    color: "#ffffff",
    background: "rgba(255, 255, 255, 0.06)",
    outline: "none",
  },
  pricingGuidanceMessage: {
    borderRadius: 16,
    padding: 14,
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid #86efac",
    color: "#ffffff",
    fontSize: 14,
    fontWeight: 900,
    lineHeight: 1.45,
  },
  pricingGuidanceMessageWarning: {
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid #fb923c",
    color: "rgba(255,255,255,0.75)",
  },
  emptyState: {
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    backdropFilter: "blur(12px)",
    padding: 18,
    borderRadius: 18,
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "rgba(255,255,255,0.75)",
    fontSize: 14,
    fontWeight: 700,
  },
  emptyStatePanel: {
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    backdropFilter: "blur(12px)",
    padding: 22,
    borderRadius: 22,
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ffffff",
  },
  emptyStateText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.5,
  },
  successStatePanel: {
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    backdropFilter: "blur(12px)",
    padding: 20,
    borderRadius: 20,
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  successStateTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ffffff",
  },
  successStateText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.5,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 240px), 1fr))",
    gap: 14,
  },
  infoCard: {
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 14,
    padding: 16,
    background: "rgba(255, 255, 255, 0.06)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  infoCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  infoCardTitle: {
    fontSize: 17,
    fontWeight: 700,
    color: "#ffffff",
  },
  infoCardSubtext: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.4,
  },
  infoCardText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.5,
  },
  infoCardCostMain: {
    fontSize: 18,
    fontWeight: 700,
    color: "#ffffff",
  },
  dashboardSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  quickActionsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 220px), 1fr))",
    gap: 16,
  },
  quickActionCard: {
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 20,
    padding: 22,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    cursor: "pointer",
    textAlign: "left",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  quickActionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    background: "linear-gradient(135deg, #f59e0b, #dc2626)",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    fontWeight: 800,
    flexShrink: 0,
  },
  quickActionContent: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  quickActionTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: "#ffffff",
  },
  quickActionText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.5,
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 180px), 1fr))",
    gap: 14,
  },
  metricCard: {
    backdropFilter: "blur(12px)",
    background: "rgba(255, 255, 255, 0.06)",
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    color: "#ffffff",
    borderRadius: 22,
    padding: 20,
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  metricCardButton: {
    width: "100%",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  metricLabel: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    marginBottom: 8,
    fontWeight: 600,
  },
  metricValue: {
    fontSize: 28,
    fontWeight: 700,
    color: "#ffffff",
  },
  dashboardTwoColumnGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 320px), 1fr))",
    gap: 16,
  },
  activityList: {
    display: "grid",
    gap: 12,
  },
  activityCard: {
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 18,
    padding: 16,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  activityLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  activityTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ffffff",
  },
  activityText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.4,
  },
  attentionList: {
    display: "grid",
    gap: 10,
  },
  attentionItem: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    padding: 14,
    borderRadius: 18,
    background: "linear-gradient(135deg, rgba(69,26,3,0.78), rgba(127,29,29,0.58))",
    color: "rgba(255,255,255,0.75)",
    border: "1px solid rgba(251,146,60,0.42)",
  },
  attentionItemButton: {
    width: "100%",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  attentionDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: "#f97316",
    marginTop: 4,
    flexShrink: 0,
  },
  attentionText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.5,
  },
  dashboardStatStack: {
    display: "grid",
    gap: 12,
  },
  dashboardStatRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: "12px 0",
    borderBottom: "1px solid rgba(148,163,184,0.18)",
  },
  dashboardStatName: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    fontWeight: 600,
  },
  dashboardStatNumber: {
    fontSize: 18,
    color: "#ffffff",
    fontWeight: 700,
  },
  sectionDivider: {
    height: 1,
    background: "#e5e7eb",
  },
  componentHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  componentList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  componentRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 120px), 1fr))",
    gap: 10,
    padding: 12,
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 16,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    alignItems: "end",
    overflow: "hidden",
  },
  componentCostNote: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    justifyContent: "flex-end",
    minWidth: 0,
  },
  componentCostLabel: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
  },
  componentCostValue: {
    fontSize: 15,
    fontWeight: 700,
    color: "#ffffff",
  },
  recipeToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 22,
    flexWrap: "wrap",
  },
  recipeToolbarLeft: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  recipeToolbarSubtitle: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 14,
    lineHeight: 1.4,
  },
  recipeToolbarRight: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
    width: "100%",
  },
  recipeSearchWrap: {
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    flex: "1 1 260px",
  },
  recipeFilterWrap: {
    minWidth: 0,
    width: "100%",
    flex: "1 1 180px",
  },
  recipeFolderList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    maxHeight: 520,
    overflowY: "auto",
    paddingRight: 4,
  },
  recipeFolderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 20,
    padding: 18,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    flexWrap: "wrap",
    boxShadow: "0 16px 28px rgba(15,23,42,0.08)",
  },
  recipeFolderMeta: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  recipeFolderName: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ffffff",
  },
  recipeFolderSubtext: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
  },
  recipeFolderStats: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  recipeFolderStat: {
    fontSize: 13,
    color: "rgba(255,255,255,0.75)",
  },
  recipeFolderActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  recipeDetailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  tableWrapper: {
    width: "100%",
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    minWidth: 980,
    overflow: "hidden",
  },
  th: {
    textAlign: "left",
    padding: "14px 12px",
    borderBottom: "1px solid #dbe4f2",
    fontSize: 12,
    color: "rgba(255,255,255,0.75)",
    background: "rgba(15,23,42,0.78)",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontWeight: 800,
  },
  td: {
    textAlign: "left",
    padding: "14px 12px",
    borderBottom: "1px solid rgba(148,163,184,0.18)",
    fontSize: 14,
    color: "#ffffff",
    verticalAlign: "top",
    background: "rgba(15,23,42,0.45)",
  },

  formGroupFull: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    gridColumn: "1 / -1",
  },
  textarea: {
    width: "100%",
    minHeight: 120,
    borderRadius: 10,
    border: "1px solid rgba(251,191,36,0.22)",
    padding: 12,
    fontSize: 14,
    fontFamily: "Arial, sans-serif",
    color: "#ffffff",
    background: "rgba(255, 255, 255, 0.06)",
    resize: "vertical",
    boxSizing: "border-box",
  },
  recipeNotesBlock: {
    whiteSpace: "pre-wrap",
    fontSize: 14,
    lineHeight: 1.6,
    color: "#ffffff",
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 12,
    padding: 14,
  },
  prepSheetSectionStack: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  prepSheetSectionCard: {
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 14,
    padding: 16,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  prepSheetSectionHeader: {
    fontSize: 18,
    fontWeight: 700,
    color: "#ffffff",
  },
  prepSheetItemList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  prepSheetItemRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 12,
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(148,163,184,0.18)",
  },
  prepSheetItemMain: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  prepSheetItemName: {
    fontSize: 15,
    fontWeight: 700,
    color: "#ffffff",
  },
  prepSheetItemMeta: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
  },
  prepSheetItemQty: {
    fontSize: 15,
    fontWeight: 700,
    color: "#ffffff",
    whiteSpace: "nowrap",
  },
  orderingSupplierList: {
    display: "grid",
    gap: 16,
  },
  orderingSupplierCard: {
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 22,
    padding: 20,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    boxShadow: "0 18px 32px rgba(15,23,42,0.08)",
  },
  orderingSupplierHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  orderingSupplierName: {
    fontSize: 18,
    fontWeight: 700,
    color: "#ffffff",
  },
  orderingRowList: {
    display: "grid",
    gap: 12,
  },
  orderingRowCard: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 1.3fr) repeat(3, minmax(140px, 0.8fr)) minmax(180px, 1fr)",
    gap: 12,
    alignItems: "end",
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 18,
    padding: 16,
  },
  orderingRowMain: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  orderingIngredientName: {
    fontSize: 15,
    fontWeight: 700,
    color: "#ffffff",
  },
  orderingIngredientMeta: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.4,
  },
  orderingSuggestionCard: {
    borderRadius: 18,
    padding: 14,
    background: "linear-gradient(135deg, rgba(127,29,29,0.85), rgba(37,99,235,0.55))",
    border: "1px solid #fbbf24",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minHeight: 88,
    justifyContent: "center",
  },
  orderingSuggestionLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "#1d4ed8",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  orderingSuggestionValue: {
    fontSize: 18,
    fontWeight: 700,
    color: "#ffffff",
  },
  orderingSuggestionCost: {
    fontSize: 13,
    color: "#1e3a8a",
    fontWeight: 600,
  },
  orderSummaryList: {
    display: "grid",
    gap: 10,
  },
  orderSummaryItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 12,
    border: "1px solid rgba(148,163,184,0.18)",
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
  },
  orderSummaryName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#ffffff",
  },
  orderSummaryMeta: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
  },
  orderSummaryQty: {
    fontSize: 14,
    fontWeight: 700,
    color: "#ffffff",
    whiteSpace: "nowrap",
  },
  sidebarBrandBadge: {
    alignSelf: "flex-start",
    padding: "6px 10px",
    borderRadius: 999,
    background: "rgba(139,92,246,0.18)",
    border: "1px solid rgba(196,181,253,0.34)",
    color: "#ddd6fe",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.12em",
  },
  brandRoast: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "#93c5fd",
  },
  navButtonInner: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  navIcon: {
    width: 40,
    height: 40,
    minWidth: 40,
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.07)",
    color: "#ffffff",
    fontSize: 16,
    fontWeight: 800,
  },
  navTextWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  navLabel: {
    fontSize: 14,
    fontWeight: 800,
    color: "inherit",
  },
  navDescription: {
    fontSize: 11,
    lineHeight: 1.35,
    color: "rgba(226,232,240,0.78)",
  },
  sidebarMiniPanel: {
    borderRadius: 22,
    padding: 16,
    background: "linear-gradient(135deg, rgba(124,58,237,0.18) 0%, rgba(37,99,235,0.18) 100%)",
    border: "1px solid rgba(196,181,253,0.18)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sidebarMiniPanelTitle: {
    fontSize: 13,
    fontWeight: 800,
    color: "#ffffff",
  },
  sidebarMiniPanelText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "rgba(255,255,255,0.75)",
  },
  sidebarStatCardHot: {
    background: "linear-gradient(135deg, rgba(124,58,237,0.26) 0%, rgba(37,99,235,0.26) 100%)",
  },
  dashboardHero: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 320px), 1fr))",
    gap: 20,
    alignItems: "stretch",
  },
  dashboardHeroCopy: {
    borderRadius: 32,
    padding: 28,
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    border: "1px solid rgba(251,191,36,0.24)",
    boxShadow: "0 24px 80px rgba(0,0,0,0.52), inset 0 0 46px rgba(245,158,11,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  dashboardHeroEyebrow: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: "#fbbf24",
  },
  heroButtonRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 8,
  },
  heroButtonRowMobile: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
  },
  mobileHeroButton: {
    width: "100%",
    minHeight: 46,
    fontSize: 13,
    fontWeight: 800,
  },
  dashboardHeroAside: {
    borderRadius: 30,
    padding: 24,
    backgroundImage: `linear-gradient(rgba(0,0,0,0.45), rgba(0,0,0,0.85)), url("/images/hero.png")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    color: "#ffffff",
    border: "1px solid rgba(251,191,36,0.24)",
    boxShadow: "0 24px 80px rgba(0,0,0,0.52), inset 0 0 46px rgba(245,158,11,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    justifyContent: "space-between",
  },
  heroAsideLabel: {
    fontSize: 11,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    color: "#93c5fd",
    marginBottom: 8,
  },
  heroAsideValue: {
    fontSize: 28,
    fontWeight: 800,
    color: "#ffffff",
    letterSpacing: "-0.05em",
  },
  heroAsideText: {
    fontSize: 14,
    lineHeight: 1.6,
    color: "rgba(255,255,255,0.75)",
    fontWeight: 600,
  },
  cardAccentMetricStack: {
    display: "grid",
    gap: 12,
  },
  cardAccentMetric: {
    background: "rgba(15,23,42,0.65)",
    borderRadius: 18,
    padding: 16,
    border: "1px solid rgba(148,163,184,0.18)",
  },
  cardAccentMetricLabel: {
    fontSize: 11,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#93c5fd",
    marginBottom: 8,
  },
  cardAccentMetricValue: {
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: "-0.03em",
    color: "#ffffff",
  },
  recipeOverviewStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 14,
  },
  recipeOverviewCard: {
    borderRadius: 22,
    padding: 18,
    background: "rgba(255, 255, 255, 0.06)",
    color: "#ffffff",
    border: "1px solid rgba(148,163,184,0.18)",
    boxShadow: "0 18px 50px rgba(0,0,0,0.28)",
  },
  recipeOverviewCardClickable: {
    cursor: "pointer",
    textAlign: "left",
    transition: "transform 0.18s ease, box-shadow 0.18s ease",
    width: "100%",
  },
  recipeOverviewLabel: {
    fontSize: 11,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#ffffff",
    marginBottom: 10,
  },
  recipeCategoryHeading: {
    fontSize: 13,
    fontWeight: 800,
    color: "#4b5563",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: 12,
  },
  quickAddBox: {
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    backdropFilter: "blur(12px)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 16,
    background: "rgba(255, 255, 255, 0.06)",
    overflow: "hidden",
  },
  quickAddResults: {
    display: "grid",
    gap: 8,
  },
  quickAddResultButton: {
    width: "100%",
    border: "1px solid rgba(148,163,184,0.18)",
    borderRadius: 14,
    background: "rgba(255, 255, 255, 0.06)",
    padding: 12,
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    textAlign: "left",
    boxSizing: "border-box",
    flexWrap: "wrap",
  },
  quickAddResultMain: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
    flex: 1,
  },
  quickAddResultName: {
    fontSize: 14,
    fontWeight: 800,
    color: "#ffffff",
    wordBreak: "break-word",
  },
  quickAddResultMeta: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    wordBreak: "break-word",
  },
  quickAddResultCost: {
    fontSize: 13,
    fontWeight: 800,
    color: "#1d4ed8",
    whiteSpace: "normal",
    textAlign: "right",
  },
  supplierComponentStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  mobileActionBar: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 45,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    padding: "12px 16px calc(12px + env(safe-area-inset-bottom, 0px))",
    background: "rgba(15,23,42,0.96)",
    borderTop: "1px solid rgba(148,163,184,0.18)",
    boxShadow: "0 -16px 32px rgba(2,6,23,0.24)",
    backdropFilter: "blur(12px)",
    boxSizing: "border-box",
  },
  smallButtonActive: {
    background: "#111827",
    color: "#ffffff",
    borderColor: "#111827",
  },
  infoCardSelected: {
    borderColor: "#111827",
    boxShadow: "0 14px 35px rgba(17, 24, 39, 0.14)",
    transform: "translateY(-1px)",
  },
  metricValueSmall: {
    fontSize: 16,
    fontWeight: 900,
    color: "#ffffff",
    lineHeight: 1.25,
    wordBreak: "break-word",
  },
  mobileActionButton: {
    width: "100%",
    minHeight: 46,
    fontSize: 13,
    fontWeight: 800,
    justifyContent: "center",
  },

  gpLogoBadge: {
    width: 70,
    height: 70,
    borderRadius: 18,
    border: "1px solid rgba(96,165,250,0.45)",
    background: "linear-gradient(135deg, rgba(15,23,42,0.95), rgba(30,64,175,0.35))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#ffffff",
    fontWeight: 900,
    fontSize: 18,
    letterSpacing: 1,
    boxShadow: "0 0 24px rgba(59,130,246,0.25)",
  },
  loginLogoImage: {
    width: "min(220px, 72vw)",
    maxWidth: "100%",
    height: "auto",
    objectFit: "contain",
    alignSelf: "center",
    filter: "drop-shadow(0 12px 28px rgba(248,113,113,0.26))",
  },
  sidebarLogoImage: {
    width: 92,
    maxWidth: "100%",
    height: "auto",
    objectFit: "contain",
    filter: "drop-shadow(0 10px 22px rgba(239,68,68,0.30))",
  },
  heroLogoBadge: {
    width: 96,
    maxWidth: "28vw",
    height: "auto",
    objectFit: "contain",
    borderRadius: 18,
    background: "rgba(0,0,0,0.28)",
    border: "1px solid rgba(251,191,36,0.24)",
    padding: 6,
    boxShadow: "0 18px 42px rgba(0,0,0,0.32)",
  },
  mainHideoutHeroContent: {
    position: "relative",
    zIndex: 2,
    width: "min(780px, 100%)",
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  mainHideoutHeroLogoRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
  },

  importActionRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    alignItems: "center",
  },
  importCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  importHelperText: {
    fontSize: 13,
    color: "#64748b",
    lineHeight: 1.5,
  },
  infoCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  infoCardHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  logoFrame: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoFrameImage: {
    width: "100%",
    maxWidth: 220,
    height: "auto",
    objectFit: "contain",
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 12,
  },
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 12,
    fontWeight: 900,
    background: "rgba(15,23,42,0.08)",
    color: "#0f172a",
  },
  tableWrap: {
    width: "100%",
    overflowX: "auto",
  },
  textareaTall: {
    minHeight: 180,
    resize: "vertical",
  },

};
